// <auto-generated />
using System;
using LuuTastyTreats.Api.Shared.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LuuTastyTreats.Api.Shared.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260906135128_AddOrdersAndAddressesSchema")]
    partial class AddOrdersAndAddressesSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Catalog.Domain.Cake", b =>
                {
                    b.Property<Guid>("CakeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("cake_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BaseImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("base_image_url");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("base_price");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean")
                        .HasColumnName("is_featured");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("CakeId")
                        .HasName("pk_cakes");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("idx_cakes_category")
                        .HasFilter("\"is_active\" = true");

                    b.ToTable("cakes", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_cakes_base_price_nonnegative", "\"base_price\" >= 0");
                        });
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Catalog.Domain.CakeCustomizationGroup", b =>
                {
                    b.Property<Guid>("CakeId")
                        .HasColumnType("uuid")
                        .HasColumnName("cake_id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<int>("MaxSelections")
                        .HasColumnType("integer")
                        .HasColumnName("max_selections");

                    b.Property<int>("MinSelections")
                        .HasColumnType("integer")
                        .HasColumnName("min_selections");

                    b.HasKey("CakeId", "GroupId")
                        .HasName("pk_cake_customization_groups");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_cake_customization_groups_group_id");

                    b.ToTable("cake_customization_groups", "catalog");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Catalog.Domain.CakeImage", b =>
                {
                    b.Property<Guid>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("image_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CakeId")
                        .HasColumnType("uuid")
                        .HasColumnName("cake_id");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.HasKey("ImageId")
                        .HasName("pk_cake_images");

                    b.HasIndex("CakeId")
                        .HasDatabaseName("ix_cake_images_cake_id");

                    b.ToTable("cake_images", "catalog");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Catalog.Domain.CakeTextField", b =>
                {
                    b.Property<Guid>("FieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("field_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CakeId")
                        .HasColumnType("uuid")
                        .HasColumnName("cake_id");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<int>("MaxLength")
                        .HasColumnType("integer")
                        .HasColumnName("max_length");

                    b.HasKey("FieldId")
                        .HasName("pk_cake_text_fields");

                    b.HasIndex("CakeId")
                        .HasDatabaseName("ix_cake_text_fields_cake_id");

                    b.ToTable("cake_text_fields", "catalog");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Catalog.Domain.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("category_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("CategoryId")
                        .HasName("pk_categories");

                    b.ToTable("categories", "catalog");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Catalog.Domain.CustomizationGroup", b =>
                {
                    b.Property<Guid>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("group_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_global");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("SelectionType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("selection_type");

                    b.HasKey("GroupId")
                        .HasName("pk_customization_groups");

                    b.ToTable("customization_groups", "catalog");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Catalog.Domain.CustomizationOption", b =>
                {
                    b.Property<Guid>("OptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("option_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("ImageOverrideUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_override_url");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("label");

                    b.Property<decimal>("PriceModifier")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price_modifier");

                    b.HasKey("OptionId")
                        .HasName("pk_customization_options");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("idx_options_group")
                        .HasFilter("\"is_available\" = true");

                    b.ToTable("customization_options", "catalog");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Identity.Domain.Address", b =>
                {
                    b.Property<Guid>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("address_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Label")
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("line1");

                    b.Property<string>("Line2")
                        .HasColumnType("text")
                        .HasColumnName("line2");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text")
                        .HasColumnName("postal_code");

                    b.Property<string>("ProvinceState")
                        .HasColumnType("text")
                        .HasColumnName("province_state");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("AddressId")
                        .HasName("pk_addresses");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_addresses_user_id");

                    b.ToTable("addresses", "identity");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Identity.Domain.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("role_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("RoleId")
                        .HasName("pk_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_name");

                    b.ToTable("roles", "identity");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Identity.Domain.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AuthProvider")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("auth_provider");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("email_verified");

                    b.Property<string>("ExternalProviderId")
                        .HasColumnType("text")
                        .HasColumnName("external_provider_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_super_admin");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", "identity");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Identity.Domain.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", "identity");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Orders.Domain.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("order_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DeliveryAddressId")
                        .HasColumnType("uuid")
                        .HasColumnName("delivery_address_id");

                    b.Property<decimal>("DeliveryFee")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("delivery_fee");

                    b.Property<string>("DeliveryMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("delivery_method");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("order_number");

                    b.Property<DateOnly>("RequestedDate")
                        .HasColumnType("date")
                        .HasColumnName("requested_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("tax_amount");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("OrderId")
                        .HasName("pk_orders");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_orders_idempotency_key");

                    b.HasIndex("OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_orders_order_number");

                    b.HasIndex("RequestedDate")
                        .HasDatabaseName("idx_orders_requested_date");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_orders_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_orders_user");

                    b.ToTable("orders", "orders");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Orders.Domain.OrderItem", b =>
                {
                    b.Property<Guid>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("order_item_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CakeId")
                        .HasColumnType("uuid")
                        .HasColumnName("cake_id");

                    b.Property<string>("CakeNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("cake_name_snapshot");

                    b.Property<string>("CustomText")
                        .HasColumnType("text")
                        .HasColumnName("custom_text");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("line_total");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("SelectedCustomizationsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("selected_customizations_json");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("OrderItemId")
                        .HasName("pk_order_items");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("idx_order_items_order");

                    b.ToTable("order_items", "orders");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Orders.Domain.OrderItemCustomizationSelection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("GroupNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("group_name_snapshot");

                    b.Property<Guid?>("OptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("option_id");

                    b.Property<string>("OptionLabelSnapshot")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("option_label_snapshot");

                    b.Property<Guid>("OrderItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_item_id");

                    b.Property<decimal>("PriceModifier")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price_modifier");

                    b.HasKey("Id")
                        .HasName("pk_order_item_customization_selections");

                    b.HasIndex("OrderItemId")
                        .HasDatabaseName("ix_order_item_customization_selections_order_item_id");

                    b.ToTable("order_item_customization_selections", "orders");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Orders.Domain.OrderStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_order_status_history");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_status_history_order_id");

                    b.ToTable("order_status_history", "orders");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Catalog.Domain.Cake", b =>
                {
                    b.HasOne("LuuTastyTreats.Api.Modules.Catalog.Domain.Category", "Category")
                        .WithMany("Cakes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_cakes_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Catalog.Domain.CakeCustomizationGroup", b =>
                {
                    b.HasOne("LuuTastyTreats.Api.Modules.Catalog.Domain.Cake", "Cake")
                        .WithMany("CustomizationGroups")
                        .HasForeignKey("CakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cake_customization_groups_cakes_cake_id");

                    b.HasOne("LuuTastyTreats.Api.Modules.Catalog.Domain.CustomizationGroup", "Group")
                        .WithMany("CakeMappings")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cake_customization_groups_customization_groups_group_id");

                    b.Navigation("Cake");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Catalog.Domain.CakeImage", b =>
                {
                    b.HasOne("LuuTastyTreats.Api.Modules.Catalog.Domain.Cake", "Cake")
                        .WithMany("Images")
                        .HasForeignKey("CakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cake_images_cakes_cake_id");

                    b.Navigation("Cake");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Catalog.Domain.CakeTextField", b =>
                {
                    b.HasOne("LuuTastyTreats.Api.Modules.Catalog.Domain.Cake", "Cake")
                        .WithMany("TextFields")
                        .HasForeignKey("CakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cake_text_fields_cakes_cake_id");

                    b.Navigation("Cake");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Catalog.Domain.CustomizationOption", b =>
                {
                    b.HasOne("LuuTastyTreats.Api.Modules.Catalog.Domain.CustomizationGroup", "Group")
                        .WithMany("Options")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customization_options_customization_groups_group_id");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Identity.Domain.Address", b =>
                {
                    b.HasOne("LuuTastyTreats.Api.Modules.Identity.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_addresses_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Identity.Domain.UserRole", b =>
                {
                    b.HasOne("LuuTastyTreats.Api.Modules.Identity.Domain.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("LuuTastyTreats.Api.Modules.Identity.Domain.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Orders.Domain.OrderItem", b =>
                {
                    b.HasOne("LuuTastyTreats.Api.Modules.Orders.Domain.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_orders_order_id");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Orders.Domain.OrderItemCustomizationSelection", b =>
                {
                    b.HasOne("LuuTastyTreats.Api.Modules.Orders.Domain.OrderItem", "OrderItem")
                        .WithMany("Selections")
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_item_customization_selections_order_items_order_item_");

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Orders.Domain.OrderStatusHistory", b =>
                {
                    b.HasOne("LuuTastyTreats.Api.Modules.Orders.Domain.Order", "Order")
                        .WithMany("StatusHistory")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_status_history_orders_order_id");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Catalog.Domain.Cake", b =>
                {
                    b.Navigation("CustomizationGroups");

                    b.Navigation("Images");

                    b.Navigation("TextFields");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Catalog.Domain.Category", b =>
                {
                    b.Navigation("Cakes");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Catalog.Domain.CustomizationGroup", b =>
                {
                    b.Navigation("CakeMappings");

                    b.Navigation("Options");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Identity.Domain.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Identity.Domain.User", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Orders.Domain.Order", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Orders.Domain.OrderItem", b =>
                {
                    b.Navigation("Selections");
                });
#pragma warning restore 612, 618
        }
    }
}
