// <auto-generated />
using System;
using LuuTastyTreats.Api.Shared.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LuuTastyTreats.Api.Shared.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Catalog.Domain.Cake", b =>
                {
                    b.Property<Guid>("CakeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("cake_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BaseImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("base_image_url");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("base_price");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean")
                        .HasColumnName("is_featured");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("CakeId")
                        .HasName("pk_cakes");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("idx_cakes_category")
                        .HasFilter("\"is_active\" = true");

                    b.ToTable("cakes", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_cakes_base_price_nonnegative", "\"base_price\" >= 0");
                        });
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Catalog.Domain.CakeCustomizationGroup", b =>
                {
                    b.Property<Guid>("CakeId")
                        .HasColumnType("uuid")
                        .HasColumnName("cake_id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<int>("MaxSelections")
                        .HasColumnType("integer")
                        .HasColumnName("max_selections");

                    b.Property<int>("MinSelections")
                        .HasColumnType("integer")
                        .HasColumnName("min_selections");

                    b.HasKey("CakeId", "GroupId")
                        .HasName("pk_cake_customization_groups");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_cake_customization_groups_group_id");

                    b.ToTable("cake_customization_groups", "catalog");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Catalog.Domain.CakeImage", b =>
                {
                    b.Property<Guid>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("image_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CakeId")
                        .HasColumnType("uuid")
                        .HasColumnName("cake_id");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.HasKey("ImageId")
                        .HasName("pk_cake_images");

                    b.HasIndex("CakeId")
                        .HasDatabaseName("ix_cake_images_cake_id");

                    b.ToTable("cake_images", "catalog");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Catalog.Domain.CakeTextField", b =>
                {
                    b.Property<Guid>("FieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("field_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CakeId")
                        .HasColumnType("uuid")
                        .HasColumnName("cake_id");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<int>("MaxLength")
                        .HasColumnType("integer")
                        .HasColumnName("max_length");

                    b.HasKey("FieldId")
                        .HasName("pk_cake_text_fields");

                    b.HasIndex("CakeId")
                        .HasDatabaseName("ix_cake_text_fields_cake_id");

                    b.ToTable("cake_text_fields", "catalog");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Catalog.Domain.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("category_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("CategoryId")
                        .HasName("pk_categories");

                    b.ToTable("categories", "catalog");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Catalog.Domain.CustomizationGroup", b =>
                {
                    b.Property<Guid>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("group_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_global");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("SelectionType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("selection_type");

                    b.HasKey("GroupId")
                        .HasName("pk_customization_groups");

                    b.ToTable("customization_groups", "catalog");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Catalog.Domain.CustomizationOption", b =>
                {
                    b.Property<Guid>("OptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("option_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("ImageOverrideUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_override_url");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("label");

                    b.Property<decimal>("PriceModifier")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price_modifier");

                    b.HasKey("OptionId")
                        .HasName("pk_customization_options");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("idx_options_group")
                        .HasFilter("\"is_available\" = true");

                    b.ToTable("customization_options", "catalog");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Identity.Domain.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("role_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("RoleId")
                        .HasName("pk_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_name");

                    b.ToTable("roles", "identity");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Identity.Domain.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AuthProvider")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("auth_provider");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("email_verified");

                    b.Property<string>("ExternalProviderId")
                        .HasColumnType("text")
                        .HasColumnName("external_provider_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_super_admin");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", "identity");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Identity.Domain.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", "identity");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Catalog.Domain.Cake", b =>
                {
                    b.HasOne("LuuTastyTreats.Api.Modules.Catalog.Domain.Category", "Category")
                        .WithMany("Cakes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_cakes_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Catalog.Domain.CakeCustomizationGroup", b =>
                {
                    b.HasOne("LuuTastyTreats.Api.Modules.Catalog.Domain.Cake", "Cake")
                        .WithMany("CustomizationGroups")
                        .HasForeignKey("CakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cake_customization_groups_cakes_cake_id");

                    b.HasOne("LuuTastyTreats.Api.Modules.Catalog.Domain.CustomizationGroup", "Group")
                        .WithMany("CakeMappings")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cake_customization_groups_customization_groups_group_id");

                    b.Navigation("Cake");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Catalog.Domain.CakeImage", b =>
                {
                    b.HasOne("LuuTastyTreats.Api.Modules.Catalog.Domain.Cake", "Cake")
                        .WithMany("Images")
                        .HasForeignKey("CakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cake_images_cakes_cake_id");

                    b.Navigation("Cake");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Catalog.Domain.CakeTextField", b =>
                {
                    b.HasOne("LuuTastyTreats.Api.Modules.Catalog.Domain.Cake", "Cake")
                        .WithMany("TextFields")
                        .HasForeignKey("CakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cake_text_fields_cakes_cake_id");

                    b.Navigation("Cake");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Catalog.Domain.CustomizationOption", b =>
                {
                    b.HasOne("LuuTastyTreats.Api.Modules.Catalog.Domain.CustomizationGroup", "Group")
                        .WithMany("Options")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customization_options_customization_groups_group_id");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Identity.Domain.UserRole", b =>
                {
                    b.HasOne("LuuTastyTreats.Api.Modules.Identity.Domain.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("LuuTastyTreats.Api.Modules.Identity.Domain.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Catalog.Domain.Cake", b =>
                {
                    b.Navigation("CustomizationGroups");

                    b.Navigation("Images");

                    b.Navigation("TextFields");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Catalog.Domain.Category", b =>
                {
                    b.Navigation("Cakes");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Catalog.Domain.CustomizationGroup", b =>
                {
                    b.Navigation("CakeMappings");

                    b.Navigation("Options");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Identity.Domain.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("LuuTastyTreats.Api.Modules.Identity.Domain.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
